apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: 209479288689.dkr.ecr.ap-south-1.amazonaws.com/my-repo:latest  # Update this with your ECR image URL
        ports:
        - containerPort: 5000
